shoppingproject/shoppingapp/urls.py
from django.urls import path
from . import views

app_name = 'shoppingapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:shoppinglist_id>/', views.detail, name="detail"),
    path('new_list', views.new_list, name="new_list"),
    path('new_item', views.new_item, name="new_item"),
    path('new_item_anlegen', views.new_item_anlegen, name="new_item_anlegen"),
    path('update_item/<int:shoppingitem_id>/', views.updateItem, name="update_item"),
    path('update_list/<int:shoppinglist_id>/', views.updateList, name='update_list'),
    path('delete_item/<int:shoppingitem_id>/', views.deleteItem, name='delete_item'),
    path('delete_list/<int:shoppinglist_id>/', views.deleteList, name='delete_list'),
]

shoppingproject/shoppingproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('shoppingapp/', include('shoppingapp.urls')),
    path('admin/', admin.site.urls),
]

shoppingproject/shoppingapp/models.py
from django.db import models

# Create your models here.

class ShoppingList(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return f"{self.name}"

class ShoppingItem(models.Model):
    name = models.CharField(max_length=100, null=False)
    quantity = models.IntegerField(default=0, null=False)
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0.00, null=False)
    done = models.BooleanField(default=False, null=False)
    shoppinglist = models.ForeignKey(ShoppingList, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.quantity} {self.price} {self.done} {self.shoppinglist}"


shoppingproject/shoppingapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import ShoppingItem, ShoppingList

class ItemForm(forms.ModelForm):

    class Meta:
        model = ShoppingItem
        fields = '__all__'

class ListForm(forms.ModelForm):

    class Meta:
        model = ShoppingList
        fields = '__all__'

shoppingproject/shoppingapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import ShoppingList, ShoppingItem
from .forms import ItemForm, ListForm
from django.urls import reverse

# Create your views here.

def index(request):
    lists = ShoppingList.objects.all()
    return render(request, 'shoppingapp/index.html', {"lists": lists})

def detail(request, shoppinglist_id):
    liste = get_object_or_404(ShoppingList, pk=shoppinglist_id)
    items = ShoppingItem.objects.filter(shoppinglist=shoppinglist_id)
    summe = 0
    for eintrag in items:
            summe += eintrag.price * eintrag.quantity
    return render(request, 'shoppingapp/detail.html', {'liste': liste, 'items': items, 'summe': summe})

def new_list(request):
    name = request.POST["name"]
    ShoppingList.objects.create(name=name)
    return HttpResponseRedirect(reverse('shoppingapp:index'))

def new_item(request):
    name = request.POST["name"]
    quantity = request.POST["quantity"]
    price = request.POST["price"]
    shoppinglist = ShoppingList.objects.get(pk=request.POST["shoppinglist"])
    ShoppingItem.objects.create(name=name,
                        quantity=quantity,
                        price=price,
                        shoppinglist=shoppinglist)
    return HttpResponseRedirect(reverse('shoppingapp:index'))

def new_item_anlegen(request):
    return render(request, 'shoppingapp/new_item_anlegen.html', {"shoppinglists": ShoppingList.objects.all()})

def updateItem(request, shoppingitem_id):
    item = get_object_or_404(ShoppingItem, pk=shoppingitem_id)

    form = ItemForm(instance=item)

    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('shoppingapp:index'))

    context = {'form': form, "aktuelle_view": "updateTask"}

    return render(request, 'shoppingapp/update_item.html', context)

def updateList(request, shoppinglist_id):
    liste = get_object_or_404(ShoppingList, pk=shoppinglist_id)

    form = ListForm(instance=liste)

    if request.method == 'POST':
        form = ListForm(request.POST, instance=liste)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('shoppingapp:index'))

    context = {'form':form}

    return render(request, 'shoppingapp/update_list.html', context)

def deleteItem(request, shoppingitem_id):
    item = get_object_or_404(ShoppingItem, pk=shoppingitem_id)
    item.delete()
    return HttpResponseRedirect(reverse('shoppingapp:index'))

def deleteList(request, shoppinglist_id):
    liste = get_object_or_404(ShoppingList, pk=shoppinglist_id)
    liste.delete()
    return HttpResponseRedirect(reverse('shoppingapp:index'))

shoppingproject/shoppingapp/templates/shoppingapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shoppingapp/style.css' %}">
    <title>{{liste.name}}</title>
</head>
<body>

    <div class="container text-white p-5 text-center">
        <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-handbag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 1a2 2 0 0 0-2 2v2h4V3a2 2 0 0 0-2-2zm3 4V3a3 3 0 1 0-6 0v2H3.361a1.5 1.5 0 0 0-1.483 1.277L.85 13.13A2.5 2.5 0 0 0 3.322 16h9.356a2.5 2.5 0 0 0 2.472-2.87l-1.028-6.853A1.5 1.5 0 0 0 12.64 5H11zm-1 1v1.5a.5.5 0 0 0 1 0V6h1.639a.5.5 0 0 1 .494.426l1.028 6.851A1.5 1.5 0 0 1 12.678 15H3.322a1.5 1.5 0 0 1-1.483-1.723l1.028-6.851A.5.5 0 0 1 3.36 6H5v1.5a.5.5 0 0 0 1 0V6h4z"/>
        </svg>
        <h1 class="display-4 p-3">{{liste.name}}</h1>
    </div>
    
    <div class='row justify-content-md-center p-2'>
        <div class="col-lg-5 p-4 bg-white rounded shadow-sm">
            <div class='row justify-content-md-center p-4'> 
                <table class='table'>
                    <tr>
                        <th>Name</th><th>Menge</th><th>Preis</th><th>Erledigt</th><th>Editieren</th><th>Löschen</th>
                    </tr>
                    {% for item in items %}
                        <tr>
                            <td class='p-3'>{{item.name}}</td>
                            <td class='p-3'>{{item.quantity}}</td>
                            <td class='p-3'>{{item.price}}</td>
                            <td class='p-3'>
                                <form>
                                    <input type="checkbox" name="item.done" {% if item.done %}checked{% endif %} onchange="submit()">
                                </form></td>
                            <td class='p-3'><a href="{% url 'shoppingapp:update_item' item.id%}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="black" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg></a></td> 
                            <td><a href="{% url 'shoppingapp:delete_item' item.id%}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="black" xmlns="http://www.w3.org/2000/svg">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                              </svg></a></td>           
                        </tr>
                    {% endfor %}
                </table>
                <table>
                    <tr>
                <td class='text-center'><p>Aktuelle Summe: {{summe}}€</p></td></tr>
                        <tr>
                <td><button type="button" class="btn"><a href="{% url 'shoppingapp:new_item_anlegen' %}" class='text-dark'>+ Neuen Eintrag anlegen</a></button></td>
                    </tr></tr>
            </table>
            </div>
        </div>
    </div>
</body>
</html>

shoppingproject/shoppingapp/templates/shoppingapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shoppingapp/style.css' %}">
    <title>Einkaufslisten</title>
</head>
<body>
    <div class="container text-white p-5 text-center">
        <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-handbag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 1a2 2 0 0 0-2 2v2h4V3a2 2 0 0 0-2-2zm3 4V3a3 3 0 1 0-6 0v2H3.361a1.5 1.5 0 0 0-1.483 1.277L.85 13.13A2.5 2.5 0 0 0 3.322 16h9.356a2.5 2.5 0 0 0 2.472-2.87l-1.028-6.853A1.5 1.5 0 0 0 12.64 5H11zm-1 1v1.5a.5.5 0 0 0 1 0V6h1.639a.5.5 0 0 1 .494.426l1.028 6.851A1.5 1.5 0 0 1 12.678 15H3.322a1.5 1.5 0 0 1-1.483-1.723l1.028-6.851A.5.5 0 0 1 3.36 6H5v1.5a.5.5 0 0 0 1 0V6h4z"/>
        </svg>
        <h1 class="display-4 p-3">Ihre Einkaufslisten</h1>
    </div>
    
    <div class="row justify-content-md-center p-2">
        <div class="col-lg-5 p-4 bg-white rounded shadow-sm">
            <div class="row justify-content-md-center">
                <table>
                {% for list in lists %}
                    <tr><td width="300em" class="p-2"><a href="{% url 'shoppingapp:detail' list.id %}" class="text-dark">{{list.name}}</a></td>
                    <td width="40px"><a href="{% url 'shoppingapp:update_list' list.id%}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="black" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 
                    14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 
                    0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/></svg></a></td>
                    <td><a href="{% url 'shoppingapp:delete_list' list.id%}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="black" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                      </svg></td></tr>
                {% endfor %}
                </table>
            </div>
            <hr>

            <div class='row justify-content-md-center'>
                <div class="container text-secondary py-2 text-center">
                    <h4>Neue Liste anlegen</h4>
                </div>
                <form action="{% url 'shoppingapp:new_list' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="name" placeholder='Name'>
                    <input type="submit" class="btn" value="Anlegen">
                </form>
            </div>  
        </div>
    </div>           
</body>
</html>

shoppingproject/shoppingapp/templates/shoppingapp/new_item_anlegen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shoppingapp/style.css' %}">
    <title>Neuer Eintrag</title>
</head>
<body>

  <div class="container text-white p-5 text-center">
    <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-handbag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 1a2 2 0 0 0-2 2v2h4V3a2 2 0 0 0-2-2zm3 4V3a3 3 0 1 0-6 0v2H3.361a1.5 1.5 0 0 0-1.483 1.277L.85 13.13A2.5 2.5 0 0 0 3.322 16h9.356a2.5 2.5 0 0 0 2.472-2.87l-1.028-6.853A1.5 1.5 0 0 0 12.64 5H11zm-1 1v1.5a.5.5 0 0 0 1 0V6h1.639a.5.5 0 0 1 .494.426l1.028 6.851A1.5 1.5 0 0 1 12.678 15H3.322a1.5 1.5 0 0 1-1.483-1.723l1.028-6.851A.5.5 0 0 1 3.36 6H5v1.5a.5.5 0 0 0 1 0V6h4z"/>
    </svg>
    <h1 class="display-4 p-3">Neues Produkt hinzufügen</h1>
  </div>

  <div class='row justify-content-md-center p-2'>
    <div class="col-lg-5 p-4 bg-white rounded shadow-sm">
      <div class='row justify-content-md-center p-4'>
        
        <form action="{% url 'shoppingapp:new_item' %}" method="post">
        {% csrf_token %}
          <div class='row'>
            <div class='col'>
              <label>Name</label></br><input type="text" name="name">
            </div>
            <div class='col'>
              <label>Quantity</label><input type="number" name="quantity">
            </div>
          </div>
          <div class='row mt-3'>
            <div class='col'>
              <label>Price</label></br><input type="number" step="0.01" name="price">
            </div>
            <div class='col'>  
              <label>Shoppingliste</label></br>
              <select name="shoppinglist">
                {% for item in shoppinglists %}
                <option value="{{item.id}}">{{item}}</option>
                {% endfor %}
              </select>
            </div>
          </div>

          <input type="submit" class="btn mt-4" value="Anlegen">
        </form>
      </div>
    </div>
  </div>


</body>
</html>

shoppingproject/shoppingapp/templates/shoppingapp/update_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shoppingapp/style.css' %}">
    <title>Eintrag bearbeiten</title>
</head>
<body>
    
    <div class="container text-white p-5 text-center">
        <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-handbag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 1a2 2 0 0 0-2 2v2h4V3a2 2 0 0 0-2-2zm3 4V3a3 3 0 1 0-6 0v2H3.361a1.5 1.5 0 0 0-1.483 1.277L.85 13.13A2.5 2.5 0 0 0 3.322 16h9.356a2.5 2.5 0 0 0 2.472-2.87l-1.028-6.853A1.5 1.5 0 0 0 12.64 5H11zm-1 1v1.5a.5.5 0 0 0 1 0V6h1.639a.5.5 0 0 1 .494.426l1.028 6.851A1.5 1.5 0 0 1 12.678 15H3.322a1.5 1.5 0 0 1-1.483-1.723l1.028-6.851A.5.5 0 0 1 3.36 6H5v1.5a.5.5 0 0 0 1 0V6h4z"/>
        </svg>
        <h1 class="display-4 p-3">Eintrag bearbeiten</h1>
    </div>
    

    <div class='row justify-content-md-center p-2'>
        <div class="col-lg-2 p-4 bg-white rounded shadow-sm">
            <div class='row justify-content-md-center p-4'>
    
            <form method='POST' action=''>
                {% csrf_token %}
    
                {{ form }}
                <input type='submit' class="btn mt-4" name='Eintrag bearbeiten'>
            </form>
    
            </div>
        </div>
    </div>
    

</body>
</html>

shoppingproject/shoppingapp/templates/shoppingapp/update_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shoppingapp/style.css' %}">
    <title>Liste bearbeiten</title>
</head>
<body>
    <div class="container text-white p-5 text-center">
        <svg width="3em" height="3em" viewBox="0 0 16 16" class="bi bi-handbag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 1a2 2 0 0 0-2 2v2h4V3a2 2 0 0 0-2-2zm3 4V3a3 3 0 1 0-6 0v2H3.361a1.5 1.5 0 0 0-1.483 1.277L.85 13.13A2.5 2.5 0 0 0 3.322 16h9.356a2.5 2.5 0 0 0 2.472-2.87l-1.028-6.853A1.5 1.5 0 0 0 12.64 5H11zm-1 1v1.5a.5.5 0 0 0 1 0V6h1.639a.5.5 0 0 1 .494.426l1.028 6.851A1.5 1.5 0 0 1 12.678 15H3.322a1.5 1.5 0 0 1-1.483-1.723l1.028-6.851A.5.5 0 0 1 3.36 6H5v1.5a.5.5 0 0 0 1 0V6h4z"/>
        </svg>
        <h1 class="display-4 p-3">Liste bearbeiten</h1>
    </div>
    

    <div class='row justify-content-md-center p-2'>
        <div class="col-lg-2 p-4 bg-white rounded shadow-sm">
            <div class='row justify-content-md-center p-4'>
    
                <form method='POST' action=''>
                    {% csrf_token %}
    
                    {{ form }}
                    <input type='submit' class="btn mt-4" name='Liste bearbeiten'>
                </form>
    
            </div>
        </div>
    </div>
    


</body>
</html>